=head1 LEGUMINOUS

A POD viewer for modules residing in the current directory or anywhere in @INC

Based on Mojolicious::Lite L<http://mojolicious.org>

=head1 FEATURES

Just request /Module::Name to get its pod.

Searchs for bare filename, filename.pod and filename.pm, in both
the current directory, lib/, and anywhere in @INC.

Links to itself for C<LE<lt>E<gt>> links which reference module names.

It rendered the previous POD atrocity correctly.

Creates a TOC from all the head1/head2 in the pod.

Requires POD::Pom and Mojolicious.

=head1 STATUS

Very alpha, but works!

=head1 BUGS

Has no quotes from Futurama or The Simpsons yet in the source,
as required by common Mojolicious modules practice.

May render some http links incorrectly.

See the issues page; open one if you have problems, or if you have
a witty quote to be added.
