=head1 LEGUMINOUS

A POD viewer for modules residing in C<@INC>.

Based on Mojolicious::Lite L<http://mojolicious.org>

=head1 FEATURES

Request /Module::Name to get its pod, or /src/Module::Name for its source code.

Searchs for bare filename, filename.pod and filename.pm in @INC.

Links to itself (/Module::Name) for C<LE<lt>E<gt>> links which reference module
names, as well as to a local hash fragments for C<LE<lt>/E<gt>>> links which
link to local sections.

It rendered the previous POD atrocity correctly.

Creates a TOC from all the head1/head2 in the pod.

Requires "just" Pod::POM::View::HTML, Path::Tiny, File::Find::Rule and
Mojolicious. Practically nothing. Easily installable via carton.

=head1 STATUS

Very alpha, but works!

=head1 BUGS

Has no quotes from Futurama or The Simpsons yet in the source,
as required by common Mojolicious modules practice.

May render some http links incorrectly. I've done my best. Patches welcome.

See the issues page; open one if you have problems, or if you have
a witty quote to be added.
